[build]
builder = "nixpacks"
buildCommand = "cd server && pip install -r requirements.txt"

[deploy]
startCommand = "cd server && python server.py"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on-failure"