[build]
builder = "nixpacks"
buildCommand = "cd server && yarn install"
rootDirectory = "/server"

[deploy]
startCommand = "node server.js"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10