[build]
builder = "nixpacks"
buildCommand = "cd server && yarn install"

[deploy]
startCommand = "cd server && yarn start"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10